---
- name: install Apache2
  hosts: N1
  become: yes 

  tasks:
  - name: install Apache2
    apt:
      name: apache2
      state: present

  - name: start Apache2
    service:
      name: apache2
      state: started

  - name: Enable Apache2
    service:
      name: apache2
      enabled: yes           
...




