---
- name: install http server
  hosts: N2
 become: yes 

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: directory

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: enable httpd
      service:
        name: httpd
        enbaled: yes           
...




